# Generated by Django 5.2.15 on 2026-07-26 21:56

import catalog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='color',
            field=models.CharField(choices=[('amber', 'Amber'), ('terracotta', 'Terracotta'), ('sage', 'Sage'), ('rose', 'Rose'), ('coral', 'Coral'), ('sand', 'Sand'), ('sky', 'Sky'), ('lavender', 'Lavender'), ('teal', 'Teal'), ('lime', 'Lime'), ('peach', 'Peach'), ('slate', 'Slate')], default=catalog.models.random_swatch, max_length=12),
        ),
    ]
