# Generated by Django 5.2.15 on 2026-06-23 17:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_trip_reminders_seeded_reminder_templatereminder_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TemplateShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'Can view'), ('edit', 'Can edit')], default='view', max_length=4)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('shared_with', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_templates', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='trips.template')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=['template', 'shared_with'], name='unique_template_share_per_user')],
            },
        ),
    ]
